### ISSUE TITLE
Change loglevel to reduce logging noise during training.

### ISSUE THREAD

**Issue by ludjac** [iterative/dvc-studio-client#15]
Very noisy logging from [dvc_studio_client/post_live_metrics.py#L169](https://github.com/iterative/dvc-studio-client/blob/main/src/dvc_studio_client/post_live_metrics.py#L169) during training. Im training a model with pytorch lightning but I believe that this issue would be valid for most ML frameworks. 

![Screenshot from 2023-03-09 10-57-22](https://user-images.githubusercontent.com/1829980/223986821-1029bb78-8cf3-462c-9628-e07c7e6ce174.png)

I suggest the loglevel for this line should be changed to DEBUG.
```python
logger.debug(f"post_studio_live_metrics `{event_type=}`")
```

I have a branch with this change but I'm not allowed to push it, otherwise I would have made a PR :)

**Comment by daavoo** [comment]
Hi @ludjac ! Thanks for the report, I will make a release with the changes.

For the record, you should be able to control the level via env var:

```shell
export DVC_STUDIO_CLIENT_LOGLEVEL="DEBUG"
```

**Comment by ludjac** [comment]
That was quick! Thanks :)
