### ISSUE TITLE
avoid using gitpython

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc-studio-client#17]
`dvc-studio-client` is using a git-binary.

https://github.com/iterative/dvc-studio-client/blob/b0aecd0831cf33d14157290ced60b36587b5041f/src/dvc_studio_client/post_live_metrics.py#L25

**Comment by shcheklein** [comment]
@skshetry could you please add some context to this?

**Comment by skshetry** [comment]
We have stopped depending on git binary in dvc because it’s slow and not always available.

But this reintroduces the dependency on it.

**Comment by daavoo** [comment]
> We have stopped depending on git 

I assume you mean dependency in code but not installation terms, right (`gitpython` is already required by `scmrepo->dvc`)? 

Slow is not really an issue here but `not always available` might be. 

Need to find an dulwich equivalent of `git_repo.git.ls_remote("--get-url") `

**Comment by skshetry** [comment]
> Slow is not really an issue here

Running the git binary is slow, especially on Windows.
