### ISSUE TITLE
STUDIO_ENDPOINT should be a base_url now

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc-studio-client#23]
Since we have multiple APIs now, STUDIO_ENDPOINT should be a base url instead of an API endpoint for live metrics.

https://github.com/iterative/dvc-studio-client/blob/485b2d8baf056882f6c7cb59438208390a045998/src/dvc_studio_client/post_live_metrics.py#L180

**Comment by daavoo** [comment]
> Or may be it should be a separate envvar like `STUDIO_URL` or `STUDIO_BASE_URL` as it's not an endpoint.

Anyhow, live metrics should not highjack a general name like STUDIO_ENDPOINT

**Comment by dberenbaum** [comment]
> > Or may be it should be a separate envvar like `STUDIO_URL` or `STUDIO_BASE_URL` as it's not an endpoint.
> 
> Anyhow, live metrics should not hijack a general name like STUDIO_ENDPOINT

TBH I feel this way about all `STUDIO_...` env vars 😅

**Comment by dberenbaum** [comment]
Is `STUDIO_ENDPOINT` documented anywhere?

**Comment by daavoo** [comment]
> TBH I feel this way about all STUDIO_... env vars 😅

So `STUDIO_TOKEN` and `STUDIO_REPO_URL` feel like that to you? I would expect them to be used to be named and used as-is for any code that interact with Studio

**Comment by daavoo** [comment]
> Is `STUDIO_ENDPOINT` documented anywhere?

No

**Comment by dberenbaum** [comment]
> So `STUDIO_TOKEN` and `STUDIO_REPO_URL` feel like that to you? I would expect them to be named and used as-is for any code that interacts with Studio

Yes, I see now we meant different things though. I think you meant that `ENDPOINT` is too generic, and I meant that `STUDIO` is too generic.
