### ISSUE TITLE
`get_studio_url` doesn't work when combined with CML

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc-studio-client#8]
It appears that CML alters the output of `git ls-remote --get-url` causing the requests to Studio to return `Permission denied or repo not found`.

Discussion in https://iterativeai.slack.com/archives/C01900GSB4J/p1675420159788629

**Comment by tapadipti** [comment]
As per [the related discussion](https://iterativeai.slack.com/archives/C01900GSB4J/p1675422723964239?thread_ts=1675420159.788629&cid=C01900GSB4J), this should be fixed in Studio, right? If yes, I'll create an issue in the Studio repo.

**Comment by daavoo** [comment]
> As per [the related discussion](https://iterativeai.slack.com/archives/C01900GSB4J/p1675422723964239?thread_ts=1675420159.788629&cid=C01900GSB4J), this should be fixed in Studio, right? If yes, I'll create an issue in the Studio repo.

It's still unclear to me where the fix should be. I will try to reproduce the bug in a more isolated setting

**Comment by daavoo** [comment]
Commented in the thread https://iterativeai.slack.com/archives/C01900GSB4J/p1675685455372039?thread_ts=1675420159.788629&cid=C01900GSB4J 

I think CML should be reverting whatever modifications are made to `.git/config`

**Comment by casperdcl** [comment]
Yes currently Studio expects something like:

```regex
https://(github|gitlab|bitbucket)\.(com|org)/\w+/\w+
```

but it should probably be more like:

```regex
https://([\S+]@)?(github|gitlab|bitbucket)\.(com|org)/\w+/\w+(\.git)?
```

/CC @nimdraugsael :)
